#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
Name     : shapelib
Version  : 1.6.0
Release  : 4
URL      : https://github.com/OSGeo/shapelib/archive/v1.6.0/shapelib-1.6.0.tar.gz
Source0  : https://github.com/OSGeo/shapelib/archive/v1.6.0/shapelib-1.6.0.tar.gz
Summary  : C API for processing ESRI Shapefiles
Group    : Development/Tools
License  : GPL-2.0+ LGPL-2.0 MIT
Requires: shapelib-bin = %{version}-%{release}
Requires: shapelib-data = %{version}-%{release}
Requires: shapelib-lib = %{version}-%{release}
Requires: shapelib-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Building on Unix
----------------
1) run ./configure to generate build scripts
Note: type ./configure --help for a list of fine-tuning options

%package bin
Summary: bin components for the shapelib package.
Group: Binaries
Requires: shapelib-data = %{version}-%{release}
Requires: shapelib-license = %{version}-%{release}

%description bin
bin components for the shapelib package.


%package data
Summary: data components for the shapelib package.
Group: Data

%description data
data components for the shapelib package.


%package dev
Summary: dev components for the shapelib package.
Group: Development
Requires: shapelib-lib = %{version}-%{release}
Requires: shapelib-bin = %{version}-%{release}
Requires: shapelib-data = %{version}-%{release}
Provides: shapelib-devel = %{version}-%{release}
Requires: shapelib = %{version}-%{release}

%description dev
dev components for the shapelib package.


%package lib
Summary: lib components for the shapelib package.
Group: Libraries
Requires: shapelib-data = %{version}-%{release}
Requires: shapelib-license = %{version}-%{release}

%description lib
lib components for the shapelib package.


%package license
Summary: license components for the shapelib package.
Group: Default

%description license
license components for the shapelib package.


%prep
%setup -q -n shapelib-1.6.0
cd %{_builddir}/shapelib-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703615964
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test
cd ../clr-build-avx2;
make test || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1703615964
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/shapelib
cp %{_builddir}/shapelib-%{version}/LICENSE-LGPL %{buildroot}/usr/share/package-licenses/shapelib/3cc956929ff9e4c1c89a2c826cdc7fec5e0b21ab || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/Shape_PointInPoly
/V3/usr/bin/csv2shp
/V3/usr/bin/dbfadd
/V3/usr/bin/dbfcat
/V3/usr/bin/dbfcreate
/V3/usr/bin/dbfdump
/V3/usr/bin/dbfinfo
/V3/usr/bin/shpadd
/V3/usr/bin/shpcat
/V3/usr/bin/shpcentrd
/V3/usr/bin/shpcreate
/V3/usr/bin/shpdata
/V3/usr/bin/shpdump
/V3/usr/bin/shpdxf
/V3/usr/bin/shpfix
/V3/usr/bin/shpinfo
/V3/usr/bin/shprewind
/V3/usr/bin/shpsort
/V3/usr/bin/shptreedump
/V3/usr/bin/shpwkb
/usr/bin/Shape_PointInPoly
/usr/bin/csv2shp
/usr/bin/dbfadd
/usr/bin/dbfcat
/usr/bin/dbfcreate
/usr/bin/dbfdump
/usr/bin/dbfinfo
/usr/bin/shpadd
/usr/bin/shpcat
/usr/bin/shpcentrd
/usr/bin/shpcreate
/usr/bin/shpdata
/usr/bin/shpdump
/usr/bin/shpdxf
/usr/bin/shpfix
/usr/bin/shpinfo
/usr/bin/shprewind
/usr/bin/shpsort
/usr/bin/shptreedump
/usr/bin/shpwkb

%files data
%defattr(-,root,root,-)
/usr/share/shapelib/shapelib-config-version.cmake
/usr/share/shapelib/shapelib-config.cmake
/usr/share/shapelib/shapelib-targets-relwithdebinfo.cmake
/usr/share/shapelib/shapelib-targets.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/shapefil.h
/usr/include/shapelib/shapefil.h
/usr/lib64/libshp.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libshp.so.1.6.0
/usr/lib64/libshp.so.1.6.0
/usr/lib64/libshp.so.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/shapelib/3cc956929ff9e4c1c89a2c826cdc7fec5e0b21ab
