#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : shapelib
Version  : 1.5.0
Release  : 1
URL      : https://github.com/OSGeo/shapelib/archive/v1.5.0.tar.gz
Source0  : https://github.com/OSGeo/shapelib/archive/v1.5.0.tar.gz
Summary  : C API for processing ESRI Shapefiles
Group    : Development/Tools
License  : GPL-2.0+ LGPL-2.0 MIT
Requires: shapelib-bin = %{version}-%{release}
Requires: shapelib-lib = %{version}-%{release}
Requires: shapelib-license = %{version}-%{release}

%description
Building on Unix
----------------
1) run ./configure to generate build scripts
Note: type ./configure --help for a list of fine-tuning options

%package bin
Summary: bin components for the shapelib package.
Group: Binaries
Requires: shapelib-license = %{version}-%{release}

%description bin
bin components for the shapelib package.


%package dev
Summary: dev components for the shapelib package.
Group: Development
Requires: shapelib-lib = %{version}-%{release}
Requires: shapelib-bin = %{version}-%{release}
Provides: shapelib-devel = %{version}-%{release}
Requires: shapelib = %{version}-%{release}

%description dev
dev components for the shapelib package.


%package lib
Summary: lib components for the shapelib package.
Group: Libraries
Requires: shapelib-license = %{version}-%{release}

%description lib
lib components for the shapelib package.


%package license
Summary: license components for the shapelib package.
Group: Default

%description license
license components for the shapelib package.


%prep
%setup -q -n shapelib-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560969626
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1560969626
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/shapelib
cp COPYING %{buildroot}/usr/share/package-licenses/shapelib/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/Shape_PointInPoly
/usr/bin/dbfadd
/usr/bin/dbfcat
/usr/bin/dbfcreate
/usr/bin/dbfdump
/usr/bin/dbfinfo
/usr/bin/shpadd
/usr/bin/shpcat
/usr/bin/shpcentrd
/usr/bin/shpcreate
/usr/bin/shpdata
/usr/bin/shpdump
/usr/bin/shpdxf
/usr/bin/shpfix
/usr/bin/shpinfo
/usr/bin/shprewind
/usr/bin/shpsort
/usr/bin/shptreedump
/usr/bin/shputils
/usr/bin/shpwkb

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libshp.so
/usr/lib64/pkgconfig/shapelib.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libshp.so.2
/usr/lib64/libshp.so.2.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/shapelib/COPYING
